### ISSUE TITLE
int8prefill: the GEMM kernel no longer compiles on macOS 27.0, and four GEMM tests hang there

### ISSUE THREAD

**Issue by krcm0209** [krcm0209/sous#123]
Found while running the #120 live gate for #122 on the M5 Pro (Apple GPU `applegpu_g17s`, macOS 27.0 build 26A428, mlx 0.32.2, mlx-vlm 0.7.1).

## What happens

`int8prefill` builds its GEMM at runtime with `mx.fast.metal_kernel`, which compiles against the OS's own `MetalPerformancePrimitives` headers. macOS 27.0's headers reject the kernel's accumulator call:

```
RuntimeError: [metal::Device] Unable to build metal library from source
mlx/backend/metal/kernels/utils.h:544:27: error: no matching member function for call to 'get_destination_cooperative_tensor'
  auto acc0 = op.template get_destination_cooperative_tensor<decltype(ct_a), decltype(ct_b), int32_t>();
/System/Library/Frameworks/MetalPerformancePrimitives.framework/Headers/MPPTensorOpsMatMul2d.h:562:3: note: candidate template ignored: requirement 'false' was not satisfied [with LeftOperandType = thread metal::cooperative_tensor<signed char, …
```

`availability()` still answers `available` (it mirrors mlx's NAX rule: macOS ≥ 26.2 and GPU generation ≥ 17), so none of the `@nax` tests skip.

**Model load: degrades as designed, does not hang.** With the default model, `int8prefill.enable(model, enabled=True)` returned `state: unavailable` about 10 s into the load, and prefill fell back to stock kernels. The warm-up's first real shape fails to compile, and the `try/except` in `enable()` catches it. So `int8_prefill = true` on macOS 27 costs one warning and the feature, not the daemon. `sous tune`'s winner-stage int8 arm fails as designed too: `suite/runner._check_int8` fails an arm the engine refuses.

One wart on that path: `reason` is the full multi-line compiler output. It goes verbatim into the load warning and into the status document's `int8_prefill.reason`. The first line is enough.

**Tests: four hang, four fail.** Each test was run alone in a fresh process with a 60 s watchdog:

| test | result |
|---|---|
| `test_gemm_is_bit_exact_with_power_of_two_metadata[64-64-32]` | hangs |
| `…[128-64-32]` | hangs |
| `…[256-192-300]` | hangs |
| `test_gemm_applies_the_row_scale` (k=128, n=64, m=40) | hangs |
| `…[1024-128-37]`, `…[1024-128-64]` | fail: compile error above |
| `test_gemm_tracks_stock_qmm_within_the_int8_noise` (k=5120) | fail: compile error above |
| `test_linear_int8_keeps_leading_dims_and_matches_qmm` (k=256, n=128, m=200) | fail: compile error above |
| every other test in the file | pass |

A hung test blocks in `.item()` (`test_int8prefill.py:195` for the first one) at 0 % CPU and never returns. The GPU works normally once the process is killed. So `uv run pytest -m "not model"` on this machine hangs forever unless you pass `--deselect tests/test_int8prefill.py`. CI cannot see any of this: its `macos-15` runners have no tensor units, and the `@nax` tests skip there.

Stock prefill is unaffected: the same machine prefilled 61K-token turns at 335–356 tok/s during the gate. That is likely because mlx's own tensor-op kernels ship precompiled in its metallib, while sous's kernel compiles against whatever headers the OS has at runtime.

## What to do

1. **Port the accumulator to the macOS 27 MPP API.** The note says the templated `get_destination_cooperative_tensor<…, int32_t>()` overload at `MPPTensorOpsMatMul2d.h:562` is now constrained away for these operand types. Check how the new header expects an int8 × int8 → int32 destination to be obtained. Check upstream oMLX (the kernel's origin, jundot/omlx#3548) and mlx's own NAX sources for a macOS 27 variant. The kernel must keep compiling on macOS 26.2+.
2. **Until then, answer `unavailable` without compiling at load.** For example, have `availability()` compile the GEMM once for a tiny shape and cache the result, so `sous status` shows a one-line reason. Or gate on the OS version. Either way, trim `reason` to the first line.
3. **Make a hang impossible in the suite.** Possibly the probe above makes the `@nax` tests skip. Otherwise run the GEMM tests under a timeout. Also find out why the small shapes hang instead of failing to compile: it may be a Metal compiler bug worth reporting to Apple.
4. **Re-measure after a port.** The README's "492 → 695 tok/s at 4K" was measured on macOS 26.x.

Related: #78 (the INT8 prefill work), #77.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
